spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300

management:
  health:
    elasticsearch:
      enabled: false
  metrics:
    export:
      influx:
        enabled: false