version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    restart: always
    ports:
    - "8086:8086"
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
    - "3000:3000"